/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Daten, die in der Tabelle angezeigt werden sollen
 */
export type Daten = string;

export interface UndefinedProps {
  data?: Daten;
}
leProps {
  data?: Data;
}
