# Name of your application. Used to uniquely configure containers.
service: analytics

# Name of the container image.
image: <%= ENV["DOCKER_ANALYTICS_IMAGE_NAME"] %>

deploy_timeout: 60

# Deploy to these servers.
servers:
  web:
    - <%= ENV["HOSTING_SERVER_IP"] %>
  # job:
  #   hosts:
  #     - 192.168.0.1
  #   cmd: bin/jobs

# Enable SSL auto certification via Let's Encrypt and allow for multiple apps on a single web server.
# Remove this section when using multiple web servers and ensure you terminate SSL at your load balancer.
#
# Note: If using Cloudflare, set encryption mode in SSL/TLS setting to "Full" to enable CF-to-app encryption.
proxy:
  ssl: true
  host: <%= ENV["NEXT_PUBLIC_ANALYTICS_DOMAIN"] %>
  # Proxy connects to your container on port 80 by default.
  app_port: 3000
  healthcheck:
    path: /api/heartbeat

# Credentials for your image host.
registry:
  # Specify the registry server, if you're not using Docker Hub
  # server: registry.digitalocean.com / ghcr.io / ...
  username: <%= ENV["DOCKER_USERNAME"] %>

  # Always use an access token rather than real password (pulled from .kamal/secrets).
  password:
    - KAMAL_REGISTRY_PASSWORD

# Configure builder setup.
builder:
  arch: amd64
  # Pass in additional build args needed for your Dockerfile.
  args:
    DATABASE_URL: "postgresql://kamal_pg:#{POSTGRES_PASSWORD}@postgres:5432/kamal_pg_production"
    DATABASE_TYPE: postgresql
# Inject ENV variables into containers (secrets come from .kamal/secrets).
#
env:
  secret:
    - POSTGRES_PASSWORD
    - DATABASE_URL
    - DATABASE_TYPE

# Aliases are triggered with "bin/kamal <alias>". You can overwrite arguments on invocation:
# "bin/kamal app logs -r job" will tail logs from the first server in the job section.
#
# aliases:
#   shell: app exec --interactive --reuse "bash"

# Use a different ssh user than root
#
# ssh:
#   user: app

# Use a persistent storage volume.
#
# volumes:
#   - "app_storage:/app/storage"

# Bridge fingerprinted assets, like JS and CSS, between versions to avoid
# hitting 404 on in-flight requests. Combines all files from new and old
# version inside the asset_path.
#
# asset_path: /app/public/assets

# Configure rolling deploys by setting a wait time between batches of restarts.
#
# boot:
#   limit: 10 # Can also specify as a percentage of total hosts, such as "25%"
#   wait: 2

# TODO add accessory for db backup job
# https://rameerez.com/kamal-tutorial-how-to-deploy-a-postgresql-rails-app/
# -> How to back up your PostgreSQL database periodically and automatically with Kamal

# Use accessory services (secrets come from .kamal/secrets).
#
accessories:
  db:
    service: postgres
    image: postgres:15
    host: <%= ENV["HOSTING_SERVER_IP"] %>
    port: 5432
    env:
      clear:
        POSTGRES_USER: "kamal_pg"
        POSTGRES_DB: "kamal_pg_production"
      secret:
        - POSTGRES_PASSWORD
    directories:
      - data:/var/lib/postgresql/data
#   redis:
#     image: valkey/valkey:8
#     host: 192.168.0.2
#     port: 6379
#     directories:
#       - data:/data
